### ISSUE TITLE
Support reload for i18n dir

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman-livereload#82]
It seems that LiveReload handles changes within the source dir well. However, it does automatically reload for your i18n_dir (locale files). This would be a big help.

**Comment by tdreyno** [comment]
Makes sense

**Comment by komor72** [comment]
@tdreyno, I know this repo still has no maintainer (?), but this feature (live-reloading of `/locales/*.yml`) works OK since long. I use it daily in my Middleman projects. Used it even in old 3.4.1. I’ve just checked now and confirmed it really works in old v3.4.1-project. 

I'm pretty sure  you can close this issue. I know, there’s no test…

**Comment by tdreyno** [comment]
Appreciate this @komor72
